spring:
  application:
    name: file-ext-admin

  datasource:
    url: jdbc:mysql://localhost:3306/file_ext_admin
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
